# Generated by Django 4.2.7 on 2024-05-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_van_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='van',
            name='description',
            field=models.CharField(blank=True, default='vans description', max_length=200, verbose_name='van description'),
        ),
    ]
