# Generated by Django 4.2.7 on 2024-05-13 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_van_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='van',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
