# Generated by Django 4.2.7 on 2024-05-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_alter_van_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='van',
            name='image',
            field=models.ImageField(blank=True, default='images/van.png', upload_to='images/', verbose_name='van image'),
        ),
    ]
