# Generated by Django 4.2.7 on 2024-05-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_alter_van_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='van',
            name='type',
            field=models.CharField(choices=[('simple', 'Simple'), ('rugged', 'Rugged'), ('luxury', 'Luxury')], max_length=20, verbose_name='van type'),
        ),
    ]
