# Generated by Django 5.0.4 on 2024-06-05 09:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_newuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='review')),
                ('text', models.CharField(max_length=200, verbose_name='comment text')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_comments', to=settings.AUTH_USER_MODEL)),
                ('van', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='van_comments', to='API.van')),
            ],
        ),
    ]
