# Generated by Django 5.0.4 on 2024-06-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_alter_van_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='van',
            name='description',
            field=models.CharField(blank=True, default='vans description', max_length=300, verbose_name='van description'),
        ),
    ]
