# Generated by Django 5.0.4 on 2024-05-06 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customre',
        ),
    ]
