# Generated by Django 4.2.7 on 2024-05-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_van_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='test',
        ),
        migrations.AlterField(
            model_name='van',
            name='image',
            field=models.ImageField(blank=True, default='images/van.png', upload_to='images/', verbose_name='van image'),
        ),
    ]
