# Generated by Django 4.2.7 on 2024-05-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_remove_newuser_first_name_remove_newuser_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='van',
            name='image',
            field=models.ImageField(blank=True, default='C:/Users/OMEN 16/Desktop/React/React-course/reactRouter-course/Vanlife/API/media/images/van.png', upload_to='images/', verbose_name='van image'),
        ),
    ]
